image_parameters:
  height_og: 1080
  img_path: ../img/static_frame_from_video.jpg
  p1:
  - 1070
  - 596
  p2:
  - 1066
  - 11
  p3:
  - 13
  - 596
  p4:
  - 9
  - 12
  size_frame: '1080'
  width_og: 607
