image_parameters:
  height_og: 800
  img_path: ../img/static_frame_from_video.jpg
  p1:
  - 529
  - 367
  p2:
  - 666
  - 260
  p3:
  - 293
  - 237
  p4:
  - 530
  - 178
  size_frame: '800'
  width_og: 600
